seq_length: &seqlen 28
model:
  base_learning_rate: 0.001
  target: ldm.models.diffusion.ddpm_time.LatentDiffusion
  params:
    linear_start: 0.0005
    linear_end: 0.1
    num_timesteps_cond: 1
    log_every_t: 40
    timesteps: 200
    loss_type: l1
    first_stage_key: "context"
    cond_stage_key: "context"
    seq_len: *seqlen
    channels: 6
    cond_stage_trainable: True
    concat_mode: False
    scale_by_std: False # True
    monitor: 'val/loss_simple_ema'
    conditioning_key: crossattn
    cond_drop_prob: 0.5

    scheduler_config: # 10000 warmup steps
      target: ldm.lr_scheduler.LambdaLinearScheduler
      params:
        warm_up_steps: [1000]
        cycle_lengths: [10000000000000]
        f_start: [1.e-6]
        f_max: [1.]
        f_min: [ 1.]

    unet_config:
      target: ldm.modules.diffusionmodules.ts_unet.UNetModel
      params:
        seq_len: *seqlen
        dims: 1
#        in_channels: 1
#        out_channels: 1
#        model_channels: 64
        in_channels: 6  # 改为变量维度
        out_channels: 6 # 改为变量维度
        model_channels: 64
        attention_resolutions: [ 1, 2, 4]   
        num_res_blocks: 2
        channel_mult: [ 1,2,4,4 ]
        num_heads: 8
        use_scale_shift_norm: True
        resblock_updown: True
        context_dim: 32
        repre_emb_channels: 32
        latent_unit: 1
        use_spatial_transformer: true
#        use_pam: true
        num_classes: 6

    first_stage_config:  # no first stage model for ts data
      target: ldm.models.autoencoder.IdentityFirstStage 

    cond_stage_config:
      target: ldm.modules.encoders.modules.DomainUnifiedPrototyper  
      params:
        dim: 32
        window: *seqlen
        latent_dim: 32  # 32 * 3
        num_latents: 16
        num_channels: 24

data:
  target: ldm.data.tsg_dataset.TSGDataModule

  params:
    data_path_dict:
      stock: "/data_new/daroms/paroms/KOVAE/logs_irgen/stock/DiffIrreg-seed=42"
    args: 0

    window: *seqlen
    val_portion: 0.1
    batch_size: 256
    num_workers: 8
    normalize: centered_pit
    drop_last: True
    reweight: True
    input_channels: 1
lightning:
#  callbacks:
#    model_checkpoint:
#      target: pytorch_lightning.callbacks.ModelCheckpoint
#      params:
##        monitor: 'val_loss'           # 监控的指标
##        mode: 'min'                   # 最小化该指标
#        save_top_k: 1                 # 只保存最好的1个模型
#        save_last: False              # 不保存最后一个模型
#        save_weights_only: True      # 保存完整模型（False）或仅权重（True）


#    image_logger:
#      target: utils_mntsg.callback_utils.TSLogger
#      params:
#        batch_frequency: 2000
#        max_images: 8
#        increase_log_steps: false


  trainer:
    benchmark: True
    max_steps: 50000
    max_epochs: 100